---

- include: hw_virt_check.yml

- include: install_kvm.yml

- include: configure_kvm.yml

- include: users.yml

- include: config_virtual_networks.yml
  tags:
    - config_virtual_networks
  when:
    - kvm_config_virtual_networks
    - kvm_virtual_networks is defined

# - include: config_storage_pools.yml
#   tags:
#     - config_storage_pools
#   when:
#     - kvm_config_storage_pools
#     - kvm_storage_pools is defined